// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqQVJCspQNgQODrp1XPeH9sLmDo7qD4mU',
    appId: '1:575595351535:web:cac71aec921958d2d7ba1a',
    messagingSenderId: '575595351535',
    projectId: 'snapspace-lite',
    authDomain: 'snapspace-lite.firebaseapp.com',
    storageBucket: 'snapspace-lite.appspot.com',
    measurementId: 'G-409PVHCN99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_YFud7fc7Mwy-HuUd_ZUB9GLXzAKaaSo',
    appId: '1:575595351535:android:ae0fa5bcf30f853ed7ba1a',
    messagingSenderId: '575595351535',
    projectId: 'snapspace-lite',
    storageBucket: 'snapspace-lite.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1qO_BCAPbsYa4DBypzdoIsEr3Pb9TQlc',
    appId: '1:575595351535:ios:1f39d7bfdae54638d7ba1a',
    messagingSenderId: '575595351535',
    projectId: 'snapspace-lite',
    storageBucket: 'snapspace-lite.appspot.com',
    iosBundleId: 'com.example.snapspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1qO_BCAPbsYa4DBypzdoIsEr3Pb9TQlc',
    appId: '1:575595351535:ios:1f39d7bfdae54638d7ba1a',
    messagingSenderId: '575595351535',
    projectId: 'snapspace-lite',
    storageBucket: 'snapspace-lite.appspot.com',
    iosBundleId: 'com.example.snapspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqQVJCspQNgQODrp1XPeH9sLmDo7qD4mU',
    appId: '1:575595351535:web:316ba4b229a73edcd7ba1a',
    messagingSenderId: '575595351535',
    projectId: 'snapspace-lite',
    authDomain: 'snapspace-lite.firebaseapp.com',
    storageBucket: 'snapspace-lite.appspot.com',
    measurementId: 'G-WY4139R2GL',
  );
}
